/**
 * Build script that embeds CSS as an inline string in TypeScript.
 * This allows the styles to be injected without external file dependencies.
 */

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const cssPath = join(__dirname, '../src/ui/viewer/styles.css');
const outputPath = join(__dirname, '../src/ui/viewer/styles-inline.ts');

const css = readFileSync(cssPath, 'utf-8');

// Escape backticks and ${} in the CSS
const escapedCss = css
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

const output = `// Auto-generated by scripts/build-styles.js - DO NOT EDIT
export const inlineStyles = \`${escapedCss}\`;
`;

writeFileSync(outputPath, output);
console.log('Generated src/ui/viewer/styles-inline.ts');
